root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ."
  bin = "./tmp/main.exe"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "tpl", "tmpl", "html"]

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[screen]
  clear_on_rebuild = false